kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-data
  namespace: go-demo-5
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
