apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
  namespace: go-demo-5
  labels:
    type: local
    author: qing.na
spec:
  storageClassName: nfs-client
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  mountOptions:
    - hard
    - nfsvers=4.1
 # persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/
    server: 172.16.0.15
    readOnly: false
